coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 2%
    patch:
      default:
        target: 60%
        threshold: 2%

comment:
  layout: "reach,diff,trend,flags,files"
  behavior: default
  require_changes: false
